### PR TITLE
(InvitingGuests/EmailVerification)

### PR DESCRIPTION
**Pull request by mrvisser**
Makes it so that when users add / update an email address manually (i.e., it isn't provided by an external authentication source), users must verify the email VIA an email that is sent to them.

Depends on:
 - https://github.com/oaeproject/3akai-ux/pull/4031
 - https://github.com/oaeproject/oae-rest/pull/15

### CODE REVIEW

**Comment by mrvisser** [comment]
This was originally implemented by Simon and reviewed by me. Unfortunately when I merged it up with master a disaster struck that erased the fact that it was a merge, and I was too deep into merging to go back. So we have lost commit history on that :/

**Comment by mrvisser** [comment]
I'm still working on the UI side of things. Just getting a few branches and PRs organized first.

**Comment by mrvisser** [comment]
Assigned to @simong for review. This is your work with just a couple additions to the templates based on designs as well as some changes to support the new workflow. There is no dedicated email verification page any more.

There will be a UI PR for this which is basically done (pending self review), but I don't think anything significant will change here anymore.

**Comment by mrvisser** [comment]
Also, sorry for nuking your commits in my merge :( I foolishly merged this to master by merging it into master, and didn't realize until I was about an hour into handling merge conflicts. My plan was to do a `git checkout -b` to a new branch with the merge result which would have retained your commit, but I accidentally `git checkout -b`'d BEFORE I commit the merge results :( The end result was that it just took the entire merge as a change set or something and ditched all your commits.

**Comment by mrvisser** [comment]
The 3akai-ux PR is in and this can now be reviewed along with its other components (see description)

**Comment by simong** [comment]
@mrvisser is this work still valid after last week's guests discussion?

**Comment by mrvisser** [comment]
@simong yessir it is, thank the lord.

**Comment by simong** [comment]
LGTM, I'll mark this on hold until https://github.com/oaeproject/3akai-ux/pull/4031 has been reviewed.

**Comment by simong** [comment]
I've gone through how a guest can be invited, create an account  and link his new account with the invited resources. This took me a while to figure out and I had a pretty good idea of how this all fits together. I can imagine that for new devs this might be completely overwhelming. Could you sketch out how all of this fits together in a wiki document perhaps?

**Comment by simong** [comment]
The above comment was made on the wrong PR. Moving it now

**Pull request merged**
