### PR TITLE
(Issue 1128) Use updated group timestamp to update libraries after join

### PR DESCRIPTION
**Pull request by mrvisser**
Addresses #1128

The unit test refactoring I did to try and reproduce this issue properly catches it happening. So regression test is baked into the general leave group tests.

### CODE REVIEW

**Comment by nicolaasmatthijs** [comment]
Assigning to @simong for review

**Comment by nicolaasmatthijs** [comment]
@mrvisser @simong : Does there need to be a "migration" step here to clean up any membership libraries that might have gotten out of sync? If so, we should also document as part of the upgrade guide.

**Comment by mrvisser** [comment]
@nicolaasmatthijs yes it would be a good idea to nuke all group memberships libraries. We can probably just truncate the LibraryIndex CF

**Comment by mrvisser** [comment]
I've added a "Next Release" section to the upgrade guide and put migration instructions there: https://github.com/oaeproject/Hilary/wiki/OAE-Upgrade-Guide#next-release

**Pull request merged**
