### PR TITLE
Searching private tenant should only ever return results from that tenant

### PR DESCRIPTION
**Pull request by sallakarppinen**
A private tenant (e.g., The Fold) currently returns search results that are outside of that tenant. All searches on a private tenant should be limited to that tenant. The "this tenant only" checkbox in the UI should also be hidden for private tenants.

screen shot 2016-07-06 at 06 17 46

### CODE REVIEW

**Comment by nicolaasmatthijs** [comment]
@sallakarppinen : This behavior should be verified in a set of comprehensive test that cover all of these different scenarios.

**Comment by nicolaasmatthijs** [comment]
Back to @sallakarppinen

**Comment by sallakarppinen** [comment]
@nicolaasmatthijs, I've modified the already existing tests to confirm the new behaviour (meaning search scope 'all' now functions like the network scope for non-admin users).

**Comment by nicolaasmatthijs** [comment]
Assigning to @mrvisser for review

**Pull request merged**
