### PR TITLE
Support etherpad 1.5.6

### PR DESCRIPTION
**Pull request by simong**
Now that Etherpad has released a version that contains everything we need, we should be able to bind to a specific version (rather than a commit)

### CODE REVIEW

**Comment by simong** [comment]
A couple of noteworthy things that will be included in this upgrade:

 * Accessibility fixes
 * Small bugfixes for mobile views
 * Small performance improvements that should improve page load times
 * Better HTML export

Check out [etherpad's changelog](https://github.com/ether/etherpad-lite/blob/develop/CHANGELOG.md) for a full reference.

**Comment by nicolaasmatthijs** [comment]
This PR looks good. However, Travis is reporting a whole bunch of test collaborative document test failures:

```
1) Content Activity Routes verify that publishing a collaborative document generates a notification:
      Uncaught AssertionError: false == true
      + expected - actual
      +true
      -false
      
      at _stream_readable.js:938:16
  2) Content Activity Routes verify an activity is generated regardless of whether there was an update to a is collaborative document since the last revision:
      Uncaught AssertionError: false == true
      + expected - actual
      +true
      -false
      
      at _stream_readable.js:938:16
  3) Collaborative documents verify basic parameter validation when joining a collaborative document:
      Uncaught AssertionError: false == true
      + expected - actual
      +true
      -false
      
      at _stream_readable.js:938:16
  4) Collaborative documents verify joining a pad respects the content permissions:
      Uncaught AssertionError: false == true
      + expected - actual
      +true
      -false
      
      at _stream_readable.js:938:16
  5) Collaborative documents verify the correct HTML is retrieved when publishing:
      Uncaught AssertionError: false == true
      + expected - actual
      +true
      -false
      
      at _stream_readable.js:938:16
  6) Collaborative documents verify that published collaborative documents are searchable:
      Uncaught AssertionError: false == true
      + expected - actual
      +true
      -false
      
      at _stream_readable.js:938:16
  7) Collaborative documents verify that published collaborative documents are restorable:
      Uncaught AssertionError: false == true
      + expected - actual
      +true
      -false
      
      at _stream_readable.js:938:16
  8) Collaborative documents verify that restoring collaborative documents is access scoped:
      Uncaught AssertionError: false == true
      + expected - actual
      +true
      -false
      
      at _stream_readable.js:938:16
  9) Collaborative documents verify that etherpad related properties cannot be set on the content object:
      Uncaught AssertionError: false == true
      + expected - actual
      +true
      -false
      
      at _stream_readable.js:938:16
  10) Collaborative documents verify etherpad document starts with empty document:
      Uncaught AssertionError: false == true
      + expected - actual
      +true
      -false
      
      at _stream_readable.js:938:16
  11) Collaborative documents verify publishing unchanged etherpad document results in no new revisions:
      Uncaught AssertionError: false == true
      + expected - actual
      +true
      -false
      
      at _stream_readable.js:938:16
  12) Collaborative documents verify empty revisions can be restored:
      Uncaught AssertionError: false == true
      + expected - actual
      +true
      -false
      
      at _stream_readable.js:938:16
  13) Content verify collabdoc editors can't delete:
      Uncaught AssertionError: false == true
      + expected - actual
      +true
      -false
      
      at _stream_readable.js:938:16
  14) Content Create content verify create collaborative document:
      Uncaught AssertionError: false == true
      + expected - actual
      +true
      -false
      
      at _stream_readable.js:938:16
  15) Content Create content verify create content with default members collaborative document:
      Uncaught AssertionError: false == true
      + expected - actual
      +true
      -false
      
      at _stream_readable.js:938:16
  16) Content Update content verify the link property cannot be updated on non-link content items:
      Uncaught AssertionError: false == true
      + expected - actual
      +true
      -false
      
      at _stream_readable.js:938:16
  17) Content Content permissions verify collabdoc editors can't change permissions:
      Uncaught AssertionError: false == true
      + expected - actual
      +true
      -false
      
      at _stream_readable.js:938:16
  18) Folders Content Integration verify folder ids can be specified when creating content:
      Uncaught AssertionError: false == true
      + expected - actual
      +true
      -false
      
      at _stream_readable.js:938:16
  19) Folders Searching for folders verify folders can be searched by messages:
      Uncaught AssertionError: false == true
      + expected - actual
      +true
      -false
      
  
  20) Preview processor Preview generation verify collaborative document processing works:
      Uncaught AssertionError: false == true
      + expected - actual
      +true
      -false
      
      at _stream_readable.js:938:16
  21) Preview processor Preview generation verify unpublished collaborative documents are ignored:
      Uncaught AssertionError: false == true
      + expected - actual
      +true
      -false
      
      at _stream_readable.js:938:16
```

**Comment by nicolaasmatthijs** [comment]
Back to @simong for follow-up

**Comment by simong** [comment]
The failures were to a misconfiguration in .travis.yml. Should be all good now

**Pull request merged**
