### PR TITLE
Change references to `/me` to `/`

### PR DESCRIPTION
**Pull request by mrvisser**
Because of https://github.com/oaeproject/3akai-ux/pull/4040, the me space will be available at `/` instead of `/me`. We should therefore change all Hilary references to `/me` to `/`

### CODE REVIEW

**Comment by mrvisser** [comment]
This is based on inviting guests, so that should be merged first

**Comment by nicolaasmatthijs** [comment]
Finished review. Back to @mrvisser for follow-up

**Comment by nicolaasmatthijs** [comment]
This is ready for merging once inviting guests and the top navigation improvements are in

**Comment by nicolaasmatthijs** [comment]
Looks good. Merged

**Pull request merged**
