### PR TITLE
Set a different fetchSize value for cassandra queries

### LINKED ISSUE #1441: Bypass the fetchSize: 5000 limitation when using cassandra driver
We need to overcome [this](https://github.com/datastax/nodejs-driver#paging).

### PR DESCRIPTION
**Pull request by brecke**
Fixes #1441

### CODE REVIEW

**Comment by sallakarppinen** [comment]
Is this a permanent solution? If not, I think we should spend a couple of days looking into a more robust option instead of adding technical debt.

**Comment by sallakarppinen** [comment]
Thanks. I think everything that ends up being added to the elasticsearch indices needs to use this method as well, since that eats whole tables.

**Comment by brecke** [comment]
Let's see if this works first and then I'll take care of the remaining caching methods 👍

**Comment by brecke** [comment]
@sallakarppinen I've applied the same querying technique to `Principals` and `Config`. I wasn't able to spot any other caching methods that would "eat whole tables", can you find any. 

All tests pass locally and on circleCI except for the flickr thing.

**Comment by sallakarppinen** [comment]
Did you check all the search index methods? The Flickr issue is on their end, but no reply on when it might be fixed yet.

**Comment by brecke** [comment]
For reference: [Flickr API user group](https://www.flickr.com/groups/api/discuss/72157686417438430/)

**Pull request merged**
